### ISSUE TITLE
New user email activation

### ISSUE THREAD

**Issue by gdyoung93** [BESTRobotics/registry#45]
Need to add proper link for account activation. The link in the email is using localhost and does not work.

**Comment by gdyoung93** [comment]
Apparently it is not needed. I was able to create account and login without activation through email link.

**Comment by the-maldridge** [comment]
As mentioned in our earlier email, activation requirements are currently disabled because the system is configured with the following directive:

```
[dev]
activate = true
```

In this mode the check in https://github.com/BESTRobotics/registry/blob/master/internal/http/accounts.go#L58 will suppress the activation initialize and create accounts that are fully activated without clicking through the email.  The email is still sent though for correctness reasons.

As for the link having the long host I have corrected the wrong host and reloaded the configuration, new emails appear to have the correct host.
